[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["Rob Harrigan <rharrigan@50onred.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
pruefung = "^0.2.1"
