[package]
name = "rust-shorty"
version = "0.1.0"
authors = ["Rob Harrigan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
pruefung = "^0.2.1"
